runtime: python39

instance_class: F2

entrypoint: gunicorn bipvote_dashboard.wsgi:application

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 4

handlers:
- url: /static
  static_dir: bipvote_dashboard/dashboard/static/dashboard/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "bipvote_dashboard.settings"
